// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBznSdNDOmwMZirrUQbATHaYWcivcz9Mio',
    appId: '1:140308323644:web:2ff8b87478b422d5059239',
    messagingSenderId: '140308323644',
    projectId: 'pal-chat-app',
    authDomain: 'pal-chat-app.firebaseapp.com',
    storageBucket: 'pal-chat-app.appspot.com',
    measurementId: 'G-EM9CJBE4MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwNbcRYX5Fspp3tsBBM-rbotqmXEqcX8',
    appId: '1:140308323644:android:8e4ddd71bd37ee9d059239',
    messagingSenderId: '140308323644',
    projectId: 'pal-chat-app',
    storageBucket: 'pal-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzHqk5Bjledxj08ELtRQy-rwwVnRL2Bjk',
    appId: '1:140308323644:ios:c55bed3a2cf1b9ad059239',
    messagingSenderId: '140308323644',
    projectId: 'pal-chat-app',
    storageBucket: 'pal-chat-app.appspot.com',
    iosClientId: '140308323644-blb4u0v21mtd2v84r2h7uprpa3133u0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzHqk5Bjledxj08ELtRQy-rwwVnRL2Bjk',
    appId: '1:140308323644:ios:c55bed3a2cf1b9ad059239',
    messagingSenderId: '140308323644',
    projectId: 'pal-chat-app',
    storageBucket: 'pal-chat-app.appspot.com',
    iosClientId: '140308323644-blb4u0v21mtd2v84r2h7uprpa3133u0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapChatApp',
  );
}
